#!/usr/bin/env python3
"""
This program scrapes Forecast.io's weather API to get the current 7-day forecast.
The current forecast is saved, as a .json file, to $PWD/dataset/daily$CURTIME.json.
"""

import sys, os
import time
import json
from forecastiopy import *

import code #DEBUG

API_KEY = open(os.path.join(os.path.dirname(__file__), "FORECASTIO_API_KEY.txt")).read().strip()
DATA_PATH = "./" # TODO: take from os.environ or from sys.argv

def main(lat, lon):

	if not os.path.isdir(DATA_PATH):
		os.mkdir(DATA_PATH) # XXX this doesn't handle if the path exists but is a file quite right

	fio = ForecastIO.ForecastIO(API_KEY, latitude=lat, longitude=lon)
	d = FIODaily.FIODaily(fio)
	#code.InteractiveConsole(locals=locals()).interact()
	print(json.dumps(d.data, indent=1, sort_keys=True))


if __name__=='__main__':
	location = sys.argv[1]
	location = [float(e) for e in location.split(",",1)]
	lat, lon = location
	
	main(lat, lon)
